# Generated by Django 3.2.16 on 2023-02-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20230224_1420'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='follow',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='follower',
            new_name='user',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'following'), name='follow'),
        ),
    ]
